import Head from 'next/head'
import { SignUp, useAuth } from '@clerk/nextjs'
import { UserButton } from '@clerk/nextjs'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect } from 'react'
import Router from 'next/router'

export default function Home() {
  const { isSignedIn } = useAuth()

  useEffect(() => {
    if (isSignedIn) Router.push('/notes')
  }, [isSignedIn])

  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">Notes App</h1>
        <SignUp redirectUrl="/notes" />

        <Link href="/notes">
          <a>Your Notes</a>
        </Link>
      </main>
    </>
  )
}
